name: Bliss
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.3.0
  curved_navigation_bar: ^1.0.3
  iconsax: ^0.0.8
  flutter_native_splash: ^2.3.9
  google_maps_flutter: ^2.5.1
  custom_info_window: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.24.2
  google_maps_webservice: ^0.0.19
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.10
  permission_handler: ^11.2.0
  open_apps_settings: ^0.0.4
  url_launcher: ^6.2.4
  webview_flutter: ^4.4.4
  flutter_barcode_scanner: ^2.0.0
  geolocator: ^10.1.0
  provider: ^6.1.1
  flutter_spinkit: ^5.2.0
  flutter_polyline_points: ^1.0.0



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/casco.png"
  adaptive_icon_background: "assets/casco.png"
  adaptive_icon_foreground: "assets/casco.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
