// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqFEJQqObbjZRKc-c-yi-WC-cJ8SZV3VQ',
    appId: '1:836713405203:web:dc2e21f2a80a2eb20558e6',
    messagingSenderId: '836713405203',
    projectId: 'bliss-db-bd5b3',
    authDomain: 'bliss-db-bd5b3.firebaseapp.com',
    databaseURL: 'https://bliss-db-bd5b3-default-rtdb.firebaseio.com',
    storageBucket: 'bliss-db-bd5b3.appspot.com',
    measurementId: 'G-4Q2YP19KCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfiUWUYzCFa6hmKKRX6YEE_jPTpfqQGhk',
    appId: '1:836713405203:android:a210c6783c425df60558e6',
    messagingSenderId: '836713405203',
    projectId: 'bliss-db-bd5b3',
    databaseURL: 'https://bliss-db-bd5b3-default-rtdb.firebaseio.com',
    storageBucket: 'bliss-db-bd5b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9EzEZm3cHQFh5D40BUJhlycV38peBWYk',
    appId: '1:836713405203:ios:915cc99a8a5a92400558e6',
    messagingSenderId: '836713405203',
    projectId: 'bliss-db-bd5b3',
    databaseURL: 'https://bliss-db-bd5b3-default-rtdb.firebaseio.com',
    storageBucket: 'bliss-db-bd5b3.appspot.com',
    androidClientId: '836713405203-jbluj9s2vel7sg0scg3l0k8kaju79fq8.apps.googleusercontent.com',
    iosClientId: '836713405203-5arpco8fc444m79fhjo0i6c90pbb44ou.apps.googleusercontent.com',
    iosBundleId: 'com.example.bliss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9EzEZm3cHQFh5D40BUJhlycV38peBWYk',
    appId: '1:836713405203:ios:41364aa9676736d30558e6',
    messagingSenderId: '836713405203',
    projectId: 'bliss-db-bd5b3',
    databaseURL: 'https://bliss-db-bd5b3-default-rtdb.firebaseio.com',
    storageBucket: 'bliss-db-bd5b3.appspot.com',
    androidClientId: '836713405203-jbluj9s2vel7sg0scg3l0k8kaju79fq8.apps.googleusercontent.com',
    iosClientId: '836713405203-d40eum6bnbsrogaj1a4a6kl8ku4gssms.apps.googleusercontent.com',
    iosBundleId: 'com.example.bliss.RunnerTests',
  );
}
